# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

#######################################################################################
# Book information
title: Stat 88 Textbook
author: Ani Adhikari
email: adhikari@berkeley.edu

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

exclude_patterns: ["LICENSE.md"]

# Website settings
logo: content/images/stat88_logo.png
html:
  favicon: content/images/favicon.ico

# Enables LaTeX, HTML images, and more.
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist


#######################################################################################
# Interact link settings

# Tells Jupyter Book to add JupyterHub links to pages
# launch_buttons:
#   notebook_interface: classic
#   jupyterhub_url: 'https://datahub.berkeley.edu'

# Remove the launch button.
sphinx:
  config:
    html_theme_options:
      launch_buttons: {}


#######################################################################################
# Option to add a Google analytics tracking code

# Navigate to https://analytics.google.com, add a new property for your jupyter book and copy the tracking id here.
google_analytics:
  mytrackingcode: